In [1]:
# Here We will learn about Indexing and Sciling in Numpy array's

In [3]:
import numpy as np

In [5]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
arrOne = arr.reshape((4,3))
print(arrOne)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
flat = arr.flatten()
print(flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [8]:
print(flat[0], flat[4], flat[3:6])

1 5 [4 5 6]


In [9]:
flat[:5]

array([1, 2, 3, 4, 5])

In [10]:
flat[3:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
flat[:10:2] # using step

array([1, 3, 5, 7, 9])

Slicing in Numpy Returns a View not a Copy

🔑 Key Concepts
Copy
1, Creates a completely new array with its own memory space.
2, Changes in the copy do not affect the original array.

View
1, Shares the same underlying data buffer as the original array.
2, Only the metadata (like shape, strides, dtype) is adjusted to represent the slice.
3, Changes in the view do affect the original array, and vice versa.

In [12]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
new_flat = flat[3:8]
print(new_flat)

[4 5 6 7 8]


In [15]:
new_flat[0] = 404

In [16]:
new_flat

array([404,   5,   6,   7,   8])

In [17]:
flat

array([  1,   2,   3, 404,   5,   6,   7,   8,   9,  10,  11,  12])

To Make a Copy we have to use .copy() method

In [18]:
flat

array([  1,   2,   3, 404,   5,   6,   7,   8,   9,  10,  11,  12])

In [19]:
flatOne = flat[3:8].copy()

In [20]:
flatOne

array([404,   5,   6,   7,   8])

In [21]:
flatOne[0] = 4

In [22]:
flatOne

array([4, 5, 6, 7, 8])

In [23]:
flat

array([  1,   2,   3, 404,   5,   6,   7,   8,   9,  10,  11,  12])

Fancy Indexing

In [25]:
arrTwo = np.array([1,9,5,2,6,7,11,40,23,67,91,39]) # this is our array
idx = [1,4,7,9,10] # this is for index
# now we retrieve the data which lies on a particular index
print(arrTwo[idx])

[ 9  6 40 67 91]


In [28]:
# Boolean Masking
temp = arrTwo[arrTwo < 10] # here we are giving a codition 
print(temp)

[1 9 5 2 6 7]
