Q1, Create a 3X3 array filled with random numbers and print its shape.

In [1]:
import numpy as np

In [4]:
# arrOne = np.random.rand(3,3) # 3x3 array of random floats in [0, 1)
arrOne = np.random.randint(1, 100, size=(3,3))
print(arrOne)

[[77 49 44]
 [15 26 91]
 [17 67 71]]


In [5]:
arrOne.shape

(3, 3)

Q2, Convert an array of floats [1.1, 2.2, 3.3, 4.4] into integers

In [10]:
arrTwo = np.array([1.1, 2.2, 3.3, 4.4])
arrTwo.dtype

dtype('float64')

In [14]:
arrThree = np.array([1.1, 2.2, 3.3, 4.4], dtype='int64')
print(arrThree, arrThree.dtype)

[1 2 3 4] int64


Q3, Use Fancy Indexing to extract even numbers from [1,2,3,4,5,6]

In [20]:
arrFour = np.array([1,2,3,4,5,6])
temp = arrFour[arrFour % 2 == 0]
temp

array([2, 4, 6])

Q4, Reshape a 1D array of size 9 into 3X3 size 

In [30]:
arrFive = np.arange(1,10,1)
temp = arrFive.reshape((3,3))
temp

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Q5, Use Boolean Masking to filter numbers greater than 50

In [34]:
arrSix = np.random.randint(40,60, size=10)
temp = arrSix[arrSix>50]
temp

array([53, 56, 54], dtype=int32)