In [2]:
import numpy as np
import time

# Using Python List
size = 1_000_000

l1 = list(range(size))
l2 = list(range(size))

start = time.time()
add = [x+y for x,y in zip(l1,l2)]
end = time.time()

print(end-start)

0.11982297897338867


In [3]:
# Using Numpy array's

size = 90_000_000

l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))

start = time.time()
add = l1+l2
end = time.time()

print(end-start)


0.6854667663574219


In [5]:
l1 = [1, 2, 3, 4]
l2 = [5, 6, 7, 8]

In [6]:
list(zip(l1, l2))

[(1, 5), (2, 6), (3, 7), (4, 8)]

In [4]:
# Numpy Array
arr = np.array([1,2,3,4,5,6,7])
print(arr)

[1 2 3 4 5 6 7]


In [7]:
# Nested array
arrOne = np.array([[1,2,3,4],[5,6,7,8]])
print(arrOne)
print('Type', type(arrOne))
print('shape', arrOne.shape)

[[1 2 3 4]
 [5 6 7 8]]
Type <class 'numpy.ndarray'>
shape (2, 4)


In [8]:
import sys
list_data = list(range(1000))
numpy_data = np.array(list_data)
print('Python list size: ', sys.getsizeof(list_data) * len(list_data), 'bytes')
print('Numpy array size: ', numpy_data.nbytes, 'bytes')

Python list size:  8056000 bytes
Numpy array size:  8000 bytes


Numpy avoids loops by applying operations to entire arrays at once using SIMD (Single Instruction, Multiple Data)

In [11]:
# Python List (loop-based)
list_square = [x**2 for x in range(10)]
print(list_square)

# Numpy array (Vectorized)
numpy_square = arrOne ** 2
print(numpy_square)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[[ 1  4  9 16]
 [25 36 49 64]]
