In [1]:
import numpy as np

In [3]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.sum(arr)

np.int64(45)

In [8]:
# some kind of indexing
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [9]:
np.sum(arr, axis=0) # it returns the column wise sum

array([12, 15, 18])

In [10]:
np.sum(arr, axis=1) # it returns the row wise sum

array([ 6, 15, 24])

Now Learn Indexing in 3D array
for 3D arrays 
The first index refers to the "depth"(sheets of data), 
Second index refers to the Rows
Third index refers to the Columns

In [11]:
arr3D = np.array([[[1,2,3], [4,5,6]],[[7,8,9], [10,11,12]]])
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
arr3D.shape 

(2, 2, 3)

In [14]:
print(arr3D[0,1,2]) # Be focused here

6


In [15]:
print(arr3D[:, 0, :])

[[1 2 3]
 [7 8 9]]
